apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyp-app-deployment
  labels:
    app: fyp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fyp-app
  template:
    metadata:
      labels:
        app: fyp-app
    spec:
      containers:
        - name: fyp-app
          image: fypcicdregistrymarkl.azurecr.io/fyp-app:PLACEHOLDER_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: PORT
              value: "8080"